# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

require 'slack/web/api/types/channel'
require 'slack/web/api/types/file'
require 'slack/web/api/types/group'
require 'slack/web/api/types/im'
require 'slack/web/api/types/user'
