# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

module Slack
  module Web
    module Api
      module Types
        class File
          attr_accessor :id
          attr_accessor :created
          attr_accessor :timestamp
          attr_accessor :name
          attr_accessor :title
          attr_accessor :mimetype
          attr_accessor :filetype
          attr_accessor :pretty_type
          attr_accessor :user
          attr_accessor :mode
          attr_accessor :editable
          attr_accessor :is_external
          attr_accessor :external_type
          attr_accessor :size
          attr_accessor :url
          attr_accessor :url_download
          attr_accessor :url_private
          attr_accessor :url_private_download
          attr_accessor :thumb_64
          attr_accessor :thumb_80
          attr_accessor :thumb_360
          attr_accessor :thumb_360_gif
          attr_accessor :thumb_360_w
          attr_accessor :thumb_360_h
          attr_accessor :permalink
          attr_accessor :edit_link
          attr_accessor :preview
          attr_accessor :preview_highlight
          attr_accessor :lines
          attr_accessor :lines_more
          attr_accessor :is_public
          attr_accessor :public_url_shared
          attr_accessor :channels
          attr_accessor :groups
          attr_accessor :initial_comment
          attr_accessor :num_stars
          attr_accessor :is_starred

          def initialize(attrs = {})
            attrs.each_pair do |k, v|
              send("#{k}=", v)
            end if attrs
          end
        end
      end
    end
  end
end
