# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

module Slack
  module Web
    module Api
      module Types
        class Im
          attr_accessor :id
          attr_accessor :is_im
          attr_accessor :user
          attr_accessor :created
          attr_accessor :is_user_deleted

          def initialize(attrs = {})
            attrs.each_pair do |k, v|
              send("#{k}=", v)
            end if attrs
          end
        end
      end
    end
  end
end
