# This file was auto-generated by lib/slack/web/api/tasks/generate.rake

module Slack
  module Web
    module Api
      module Types
        class User
          attr_accessor :id
          attr_accessor :name
          attr_accessor :deleted
          attr_accessor :color
          attr_accessor :profile
          attr_accessor :is_admin
          attr_accessor :is_owner
          attr_accessor :is_primary_owner
          attr_accessor :is_restricted
          attr_accessor :is_ultra_restricted
          attr_accessor :has_files

          def initialize(attrs = {})
            attrs.each_pair do |k, v|
              send("#{k}=", v)
            end if attrs
          end
        end
      end
    end
  end
end
